server:
  port: 9100
spring:
  application:
    name: yan-base  #微服务名称
  datasource: #数据库连接参数
    url: jdbc:mysql://localhost:3306/yan_base?characterEncoding=UTF8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true  #打印sql
    database: mysql
    generate-ddl: false #自动建表