server:
  port: 9100
spring:
  application:
    name: yan-base  #微服务名称
  datasource: #数据库连接参数
    url: jdbc:mysql://localhost:3306/yan_base?characterEncoding=UTF8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
#  jpa:
#    show-sql: true  #打印sql
#    database: mysql
#    generate-ddl: false #自动建表
# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.yan
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis-config.xml

# PageHelper分页插件
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql